// THIS FILE IS AUTOMATICALLY GENERATED
// DON'T CHANGE IT IN ORDER TO MAKE IT PROPERLY WORK!
export const routeNames = {
  spaces: 'spaces',
  me: 'me',
  map: 'map',
  index: 'index',
  auth: 'auth',
  addSpace: 'add_space'
}
